### ISSUE TITLE
Slack community

### ISSUE THREAD

**Issue by aberba** [kleinrein/awesome-elementaryos#1]
There is a slack community at elementaryoscommunity.slack.com. It has a self invite heroku app but I don't recall the URL. A lot of people are active there.

**Comment by kleinrein** [comment]
I haven't heard about it. No luck googling it. Tell me if you find the link to the self invite heroku app :+1:

**Comment by aberba** [comment]
Got it. Here you go https://elementarycommunity.herokuapp.com/

**Comment by aberba** [comment]
A lot of folks are there

**Comment by kleinrein** [comment]
Great. Thanks. Added, and closing issue.
